[package]
name = "petalsonic"
description = "Real-time safe native spatial audio library for Rust"
version = "0.8.0"
edition = "2024"
authors = ["Ruitian Yang <ruitian0716@gmail.com>"]
license = "MIT"
keywords = ["audio", "spatial", "3d", "hrtf", "game"]
categories = ["multimedia::audio", "game-development"]
repository = "https://github.com/tr-nc/petalsonic"
readme = "README.md"

[dependencies]
symphonia = "0.5.4"
cpal = "0.15.3"
rubato = "0.14.1"
realfft = "3.5.0"
crossbeam-channel = "0.5.13"
ringbuf = "0.4.7"
log = { workspace = true }
glam = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.54", features = ["Win32_Foundation", "Win32_System_Com"] }
