[package]
name = "petalsonic-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
petalsonic = { path = "../petalsonic" }
env_logger = "0.10"
log = { workspace = true }
anyhow = "1.0"
eframe = "0.29"
egui = "0.29"
